# SPDX-FileCopyrightText: © 2024 Christopher Woods <Christopher.Woods@bristol.ac.uk>
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = "CLAUDE.md"
SPDX-FileCopyrightText = "© 2025 Christopher Woods <Christopher.Woods@bristol.ac.uk>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "CHANGELOG.md"
SPDX-FileCopyrightText = "© 2025 Christopher Woods <Christopher.Woods@bristol.ac.uk>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "filesystem/utils/lfs"
SPDX-FileCopyrightText = "© 2026 Christopher Woods <Christopher.Woods@bristol.ac.uk>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

